version: 2.1

executors:
  python-3_08:
    docker:
    - image: python:3.8.20
  python-3_09:
    docker:
    - image: python:3.9.20
  python-3_10:
    docker:
    - image: python:3.10.15

commands:
  build:
    steps:
    - run:
        name: Install dependencies
        command: pip install wheezy.template coverage codecov
    - checkout
    - run:
        name: Run tests
        command: coverage run -m unittest
    - run:
        name: Upload coverage
        command: codecov

jobs:
  py308:
    executor: python-3_08
    steps:
    - build

  py309:
    executor: python-3_09
    steps:
    - build

  py310:
    executor: python-3_10
    steps:
    - build

workflows:
  version: 2
  build:
    jobs:
    - py308
    - py309
    - py310
